/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChannelsChannelIdRouteRouteImport } from './routes/channels/$channelId/route'
import { Route as ChannelsChannelIdChatsChatIdRouteImport } from './routes/channels/$channelId/chats/$chatId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsChannelIdRouteRoute = ChannelsChannelIdRouteRouteImport.update({
  id: '/channels/$channelId',
  path: '/channels/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsChannelIdChatsChatIdRoute =
  ChannelsChannelIdChatsChatIdRouteImport.update({
    id: '/chats/$chatId',
    path: '/chats/$chatId',
    getParentRoute: () => ChannelsChannelIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/channels/$channelId': typeof ChannelsChannelIdRouteRouteWithChildren
  '/channels/$channelId/chats/$chatId': typeof ChannelsChannelIdChatsChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/channels/$channelId': typeof ChannelsChannelIdRouteRouteWithChildren
  '/channels/$channelId/chats/$chatId': typeof ChannelsChannelIdChatsChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/channels/$channelId': typeof ChannelsChannelIdRouteRouteWithChildren
  '/channels/$channelId/chats/$chatId': typeof ChannelsChannelIdChatsChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/channels/$channelId'
    | '/channels/$channelId/chats/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/channels/$channelId'
    | '/channels/$channelId/chats/$chatId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/channels/$channelId'
    | '/channels/$channelId/chats/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChannelsChannelIdRouteRoute: typeof ChannelsChannelIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/$channelId': {
      id: '/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof ChannelsChannelIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/$channelId/chats/$chatId': {
      id: '/channels/$channelId/chats/$chatId'
      path: '/chats/$chatId'
      fullPath: '/channels/$channelId/chats/$chatId'
      preLoaderRoute: typeof ChannelsChannelIdChatsChatIdRouteImport
      parentRoute: typeof ChannelsChannelIdRouteRoute
    }
  }
}

interface ChannelsChannelIdRouteRouteChildren {
  ChannelsChannelIdChatsChatIdRoute: typeof ChannelsChannelIdChatsChatIdRoute
}

const ChannelsChannelIdRouteRouteChildren: ChannelsChannelIdRouteRouteChildren =
  {
    ChannelsChannelIdChatsChatIdRoute: ChannelsChannelIdChatsChatIdRoute,
  }

const ChannelsChannelIdRouteRouteWithChildren =
  ChannelsChannelIdRouteRoute._addFileChildren(
    ChannelsChannelIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChannelsChannelIdRouteRoute: ChannelsChannelIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
